services:
  pizzeria:
    build: .
    container_name: pizzeria
    ports:
      - "2020:8080"
    env_file:
      - .env
    environment:
      - APP_ENV=production
    restart: unless-stopped
    volumes:
      - pizzeria_db_data:/app/db
      - pizzeria_images:/app/static/images/menu

volumes:
  pizzeria_db_data:
    name: pizzeria_db_data
  pizzeria_images:
    name: pizzeria_images
