services:
  pizzeria:
    build: .
    container_name: pizzeria
    ports:
      - "2020:8080"
    env_file:
      - .env
    environment:
      - APP_ENV=production
    restart: unless-stopped
    volumes:
      - ./db:/app/db
      - ./static/images/menu:/app/static/images/menu
